# Generated by Django 6.0.4 on 2026-04-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=3)),
                (
                    "hand",
                    models.CharField(
                        choices=[("R", "Right"), ("L", "Left"), ("U", "Unknown")],
                        default="R",
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("turned_pro", models.IntegerField(blank=True, null=True)),
                ("current_rank", models.IntegerField(blank=True, null=True)),
                ("best_rank", models.IntegerField(blank=True, null=True)),
                ("height_cm", models.IntegerField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="players/photos"
                    ),
                ),
                (
                    "atp_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["current_rank"],
            },
        ),
    ]
