# Generated by Django 6.0.4 on 2026-05-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
