# Generated by Django 6.0.4 on 2026-05-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_player_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
