# Generated by Django 6.0.4 on 2026-04-28 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tournament_name", models.CharField(max_length=200)),
                ("tournament_date", models.DateField(blank=True, null=True)),
                (
                    "surface",
                    models.CharField(
                        choices=[
                            ("HR", "Hard"),
                            ("CL", "Clay"),
                            ("GR", "Grass"),
                            ("CP", "Carpet"),
                            ("UN", "Unknown"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "round",
                    models.CharField(
                        choices=[
                            ("R128", "Top 128"),
                            ("R64", "Top 64"),
                            ("R32", "Top 32"),
                            ("R16", "Top 16"),
                            ("QF", "Quater-Final"),
                            ("SF", "Semi-Final"),
                            ("F", "Final"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("G", "Grand Slam"),
                            ("M", "Masters"),
                            ("A", "ATP"),
                            ("C", "Challenger"),
                        ],
                        max_length=1,
                    ),
                ),
                ("score", models.CharField(max_length=25)),
                ("minutes", models.IntegerField(blank=True, null=True)),
                ("w_aces", models.IntegerField(blank=True, null=True)),
                ("w_df", models.IntegerField(blank=True, null=True)),
                ("w_svpt", models.IntegerField(blank=True, null=True)),
                ("w_1stIn", models.IntegerField(blank=True, null=True)),
                ("w_1stWon", models.IntegerField(blank=True, null=True)),
                ("w_2ndWon", models.IntegerField(blank=True, null=True)),
                ("w_bpSaved", models.IntegerField(blank=True, null=True)),
                ("w_bpFaced", models.IntegerField(blank=True, null=True)),
                ("l_aces", models.IntegerField(blank=True, null=True)),
                ("l_df", models.IntegerField(blank=True, null=True)),
                ("l_svpt", models.IntegerField(blank=True, null=True)),
                ("l_1stIn", models.IntegerField(blank=True, null=True)),
                ("l_1stWon", models.IntegerField(blank=True, null=True)),
                ("l_2ndWon", models.IntegerField(blank=True, null=True)),
                ("l_bpSaved", models.IntegerField(blank=True, null=True)),
                ("l_bpFaced", models.IntegerField(blank=True, null=True)),
                ("winner_rank", models.IntegerField(blank=True, null=True)),
                ("loser_rank", models.IntegerField(blank=True, null=True)),
                (
                    "atp_match_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lose_matches",
                        to="players.player",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_matches",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-tournament_date"],
            },
        ),
    ]
